version: "3.7"
services:
  #dados para crição do container do mysql
  mysql_db:
    image: "mysql:8.0" #imagem vem do dockerhub, equivale ao from
    container_name: mysqlserveremprescar #nomeando container
    ports: # redirecionando as portas
      - "3308:3306" # primeira meu pc e segunda porta container
    environment: #variaveis de ambientes do mysql
      MYSQL_DATABASE: emprescar
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes: #meu hd externo para o container
      - db_mysql:/var/lib/mysql
    networks: # uma rede entre os container
      - servers
  ##fim do mysql

volumes:
  db_mysql:

networks:
  servers:
    driver: bridge